version: '3.8'
services:
  app:
    build: .
    container_name: todo
    ports:
      - '9876:9876'
    environment:
      - NODE_ENV=production
      - DB_SSL=true
    env_file:
      - .env
    restart: unless-stopped
    